name: build site

on:
  push:
    paths:
      - 'Prototypes/web/**'
      - '.github/workflows/**'

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: get repo web
        uses: actions/checkout@v4
      
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: copy files
        env:
          MQTT_ADMIN_USERNAME: ${{ secrets.MQTT_ADMIN_USERNAME }}
          MQTT_ADMIN_PASSWORD: ${{ secrets.MQTT_ADMIN_PASSWORD }}
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" Prototypes/web/ gruppe1@${{ vars.SERVER_IP }}:/srv
          ssh -i ~/.ssh/id_rsa gruppe1@${{ vars.SERVER_IP }} 'echo "MQTT_ADMIN_USERNAME=$MQTT_ADMIN_USERNAME" > /srv/.env'
          ssh -i ~/.ssh/id_rsa gruppe1@${{ vars.SERVER_IP }} 'echo "MQTT_ADMIN_PASSWORD=$MQTT_ADMIN_PASSWORD" >> /srv/.env'

      - name: make executable
        run: ssh -i ~/.ssh/id_rsa gruppe1@${{ vars.SERVER_IP }} 'chmod +x /srv/build.sh'

      - name: run build script
        run: ssh -i ~/.ssh/id_rsa gruppe1@${{ vars.SERVER_IP }} 'bash /srv/build.sh'
