name: build site

on:
  push:
    paths:
      - 'Prototypes/web/**'

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: get repo web
        uses: actions/checkout@v4
      
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H midjo.me >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: copy files
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" Prototypes/web/ gruppe1@midjo.me:/home/gruppe1/repo/web/

      - name: make executable
        run: ssh -i ~/.ssh/id_rsa gruppe1@midjo.me 'chmod +x /home/gruppe1/repo/web/build.sh'


      - name: run build script
        run: ssh -i ~/.ssh/id_rsa gruppe1@midjo.me 'bash /home/gruppe1/repo/web/build.sh'





